.TH "LINUX-SHOW-PLAYER" "1" "December 03, 2017" "Version 0.5" "Usage and Commands"
.SH NAME
LINUX-SHOW-PLAYER - Sound player designed for stage productions
.SH SYNOPSIS
linux-show-player [\-h] [\-f FILE] [\-l {debug,info,warning}] [\-\-locale LOCALE]
.SH DESCRIPTION
 Linux Show Player (or LiSP for short) is a free cue player designed for
 sound-playback in stage production. The goal of the project is to provide a
 complete playback software for musical plays, theater shows and similar.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help message and exit
.TP
\fB\-f\fR, \fB\-\-file FILE\fR 
Session file path
.TP
\fB\-l\fR, \fB\-\-log {debug,info,warning}\fR
Log level
.TP
\fB\ \fB\-\-locale LOCALE\fR
Force specified locale
.SH AUTHOR
linux-show-player was written by Francesco Ceruti <ceppofrancy@gmail.com>
.PP
This manual page was written by Josue Ortega <josue@debian.org>,
for the Debian project (and may be used by others).
