name: Poetry Lockfile rebuild

on:
  workflow_dispatch:
  push:
    branches:
    - ci-lockfile

jobs:

  rebuild:
    name: Lockfile Rebuild
    runs-on: ${{ matrix.sys.os }}

    env:
      # As of 1.2.0b2 poetry tries to access the system Keyring for more actions than it did
      # before. This causes problems on the Ubuntu CI - but not on Windows - for reasons that
      # are unclear. (Backend installed but not running? System not capable of prompting a
      # user to login to unlock the keychain as it's a CI system?)
      #
      # @see https://github.com/python-poetry/poetry/issues/1917
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

    defaults:
      run:
        shell: ${{ matrix.sys.shell }}

    strategy:
      fail-fast: false
      matrix:
        sys:
        - os: windows-2019
          shell: msys2 {0}
        - os: ubuntu-latest
          shell: bash

        poetVers:
        - 1.4.0
        - 1.3.1
        - 1.3.0
        - 1.2.2
        - 1.2.1
        - 1.2.0

    steps:

    # This should closely mirror the msys2-ci workflow file
    - name: Install and Configure Msys2
      if: ${{ matrix.sys.os == 'windows-2019' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        update: true
        install: >
          git
        pacboy: >
          cairo:p
          gcc:p
          gobject-introspection:p
          gstreamer:p
          gst-plugins-good:p
          liblo:p
          pkgconf:p
          python-gobject:p
          python-pip:p
          python-pyqt5:p
          qt5-svg:p
          rtmidi:p

    - name: Update pip
      run: |
        python -m pip install -U pip

    - name: Install Poetry via pip
      run: |
        pip install poetry==${{ matrix.poetVers }}
        pip list | grep poetry

    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    # Without this, we get a series of "MaxRetryError" errors when rebuilding the lockfile on
    # Windows, seemingly caused by not being able to verify certificates.
    #
    # The VM version of git appears to be configured to use a file that may assist with this,
    # however attempting to tell the MSys2 version of git to use the exact same config fails
    # with the same error.
    #
    # I suspect that this may be some fault or shortcoming in Dulwich, which is what poetry uses
    # instead of querying the git client.
    # 
    # We still need to install a version of git via MSys2, as a git client is needed to clone
    # dependencies not available via pip, and the VM version of git can seemingly not be found
    # when inside an MSys2 shell.
    - name: Force system git client
      if: ${{ matrix.sys.os == 'windows-2019' }}
      run: |
        poetry config experimental.system-git-client true

    - name: Rebuild lockfile
      run: |
        poetry lock -v

    # Each of the jobs *should* generate the same (platform-agnostic) lockfile.
    # However they might not, so upload all of them for comparison.
    - name: Upload lockfile
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.sys.os }}__${{ matrix.poetVers }}__poetry.lock
        path: poetry.lock
